name: bia-eb-main
services:
  server:
    environment:
      DB_PORT: "5432"
      DB_PWD: postgres
      DB_USER: postgres
    image: 730335588602.dkr.ecr.us-east-1.amazonaws.com/biadev:dd6466e
    networks:
      default: null
    ports:
      - mode: ingress
        target: 8080
        published: "80"
        protocol: tcp
networks:
  default:
    name: bia-eb-main_default
